version: '3'
services:
    nginx:
        image: nginx:1.21.4
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ..:/var/www/html
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        environment:
            TZ: "Asia/Shanghai"
        depends_on:
           - "php"
    php:
        build:
            context: ./php
            dockerfile: Dockerfile
        image: php:local-dev
        container_name: "php"
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ..:/var/www/html
            - ./php/conf/php.ini:/usr/local/etc/php/php.ini

    # db:
    #     image: mariadb:10.7.1
    #     container_name: db
    #     restart: always
    #     ports:
    #         - "3306:3306"
    #     volumes:
    #         - ./mysql/conf:/etc/mysql/conf.d
    #         - ./mysql/data:/var/lib/mysql
    #     environment:
    #         MYSQL_ROOT_PASSWORD: "root password"
    #         MYSQL_DATABASE: "dbname"
    #         MYSQL_USER: "username"
    #         MYSQL_PASSWORD: "user password"
