version: '3'
services:
    nginx:
        image: docker.io/bitnami/nginx:latest
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - .:/app
            - ./docker/app.conf:/opt/bitnami/nginx/conf/server_blocks/app.conf
        environment:
            TZ: "Asia/Shanghai"
        depends_on:
           - "phpfpm"
    phpfpm:
        image: docker.io/bitnami/php-fpm:latest
        volumes:
            - .:/app
            - ./docker/custom.ini:/opt/bitnami/php/etc/conf.d/custom.ini
        environment:
            TZ: "Asia/Shanghai"

    # db:
    #     image: mariadb:10.7.1
    #     container_name: db
    #     restart: always
    #     ports:
    #         - "3306:3306"
    #     volumes:
    #         - ./mysql/conf:/etc/mysql/conf.d
    #         - ./mysql/data:/var/lib/mysql
    #     environment:
    #         MYSQL_ROOT_PASSWORD: "root password"
    #         MYSQL_DATABASE: "dbname"
    #         MYSQL_USER: "username"
    #         MYSQL_PASSWORD: "user password"
