version: "3"
services:
    nginx:
        image: docker.io/bitnami/nginx:latest
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/app
            - ./nginx/server_blocks:/opt/bitnami/nginx/conf/server_blocks
        environment:
            TZ: "Asia/Shanghai"
        depends_on:
            - "phpfpm"
    phpfpm:
        build: ./phpfpm
        image: myapp/phpfpm
        container_name: phpfpm
        volumes:
            - .:/app
            - ./phpfpm/etc/conf.d/custom.ini:/opt/bitnami/php/etc/conf.d/custom.ini
        environment:
            TZ: "Asia/Shanghai"

    db:
        image: docker.io/bitnami/mariadb:latest
        container_name: db
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./mariadb/conf/my.cnf:/opt/bitnami/mariadb/conf/my.cnf:ro
            - ./mariadb/data:/bitnami/mariadb/data
        environment:
            TZ: "Asia/Shanghai"
            MARIADB_ROOT_PASSWORD: "root password"
        #   MARIADB_DATABASE: "dbname"
        #   MARIADB_USER: "username"
        #   MARIADB_PASSWORD: "user password"