services:
    geth-node1:
        image: ethereum/client-go:stable
        container_name: geth-node1
        ports:
            - 8545:8545
        volumes:
            - ./node-1:/data/node
            - ./conf:/data/conf
        tty: true
        entrypoint: /data/conf/entrypoint.sh
    geth-node2:
        image: ethereum/client-go:stable
        container_name: geth-node2
        ports:
            - 9545:8545
        volumes:
            - ./node-2:/data/node
            - ./conf:/data/conf
        tty: true
        entrypoint: /data/conf/entrypoint.sh
